[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde={version="1.0.140", features = ["derive"] }
serde_json="1.0.82"
uuid={ version = "1.1.2", features = ["v4","js"] }


